on:
  schedule:
  # Run every Sunday at midnight
  - cron: '0 0 * * 0'

jobs:
  download-project-string:
    name: Download translations from Localazy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}
        - uses: localazy/download@v1
          with:
            read_key: ${{ secrets.LOCALAZY_READ_KEY }}
            write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
           commit_message: Commit latest translations from Localazy.
